name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    env:
      OPENMODELICAHOME: '/usr'
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: "Set up OpenModelica Compiler"
        uses: AnHeuermann/setup-openmodelica@v0.6
        with:
          version: 'stable'
          packages: |
            omc
          libraries: |
            'Modelica 4.0.0'
          omc-diff: true

      - name: "Test OpenModelica"
        run: "make -C Testing openmodelica"

      - name: "Upload openmodelica.log"
        uses: actions/upload-artifact@v3
        with:
          name: openmodelica.log
          path: Testing/openmodelica.log

      - name: "Look for failing tests"
        run: |
          grep "\(^ - \)\|\(... equation mismatch\)" Testing/openmodelica.log | true
          grep -i "^== 0 out of [0-9]* tests failed" Testing/openmodelica.log
